DROP TABLE `districts`;
DROP TABLE `orderbooks`;
DROP TABLE `cartbooks`;
DROP TABLE `favorites`;
DROP TABLE `books`;
DROP TABLE `carts`;
DROP TABLE `orders`;
DROP TABLE `addresses`;
DROP TABLE `users`;
